// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:957ce3dd-3dbd-48c6-b225-66bad95cd9af",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_yw5Purm5M",
    "aws_user_pools_web_client_id": "4qcoacsp2r9m7vr5k850ep4nog",
    "oauth": {}
};


export default awsmobile;
